
---

apiVersion: v1
kind: Service
metadata:
  name: demo-static-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: demo-static-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-static-app
spec:
  selector:
    matchLabels:
      service: demo-static-app
  replicas: 1
  template:
    metadata:
      labels:
        service: demo-static-app
    spec:
      containers:
      - image: nishedcob/demo-static-app:73812d2
        name: demo-static-app
        ports:
        - containerPort: 80
      restartPolicy: Always
