
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: giteadb
  name: giteadb
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: giteadb
status:
  loadBalancer: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: giteadb
  name: giteadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: giteadb
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: '"Gitea: Git with a cup of tea"'
        - name: DB_HOST
          value: '"giteadb:5432"'
        - name: DB_NAME
          value: '"gitea"'
        - name: DB_PASSWD
          value: '"gitea"'
        - name: DB_TYPE
          value: '"postgres"'
        - name: DB_USER
          value: '"gitea"'
        - name: DISABLE_REGISTRATION
          value: '"false"'
        - name: DOMAIN
          value: '"0.0.0.0"'
        - name: POSTGRES_DB
          value: gitea
        - name: POSTGRES_PASSWORD
          value: gitea
        - name: POSTGRES_USER
          value: gitea
        - name: REQUIRE_SIGNIN_VIEW
          value: '"false"'
        - name: RUN_MODE
          value: '"prod"'
        - name: SECRET_KEY
          value: '"55356c9142ab77aefabebeca"'
        - name: SSH_DOMAIN
          value: '"0.0.0.0"'
        image: postgres:12
        name: giteadb
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /tmp/dumps
          name: giteadb-dumps
        - mountPath: /var/lib/postgresql/data
          name: giteadb-data
        - mountPath: /docker-entrypoint-initdb.d/gitea.sql
          name: giteadb-restore-dump
      restartPolicy: Always
      volumes:
      - name: giteadb-dumps
        hostPath:
          path: /giteadb/dumps
          type: Directory
      - name: giteadb-data
        hostPath:
          path: /giteadb/data
          type: Directory
      - name: giteadb-restore-dump
        hostPath:
          path: /giteadb/restore/gitea.sql
          type: Directory
status: {}
