
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: gitea
  name: gitea
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  - name: "2222"
    port: 2222
    targetPort: 22
  selector:
    io.kompose.service: gitea
status:
  loadBalancer: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: gitea
  name: gitea
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gitea
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: '"Gitea: Git with a cup of tea"'
        - name: DB_HOST
          value: '"giteadb:5432"'
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gitea
              key: db_DB_NAME
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea
              key: db_DB_PASSWD
        - name: DB_TYPE
          value: '"postgres"'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gitea
              key: db_DB_USER
        - name: DISABLE_REGISTRATION
          value: '"false"'
        - name: DOMAIN
          value: '"0.0.0.0"'
        - name: REQUIRE_SIGNIN_VIEW
          value: '"false"'
        - name: RUN_MODE
          value: '"prod"'
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: gitea
              key: gitea_SECRET_KEY
        - name: SSH_DOMAIN
          value: '"0.0.0.0"'
        image: gitea/gitea:1.9.5
        name: gitea
        ports:
        - containerPort: 3000
        - containerPort: 22
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: gitea-data
      restartPolicy: Always
      volumes:
      - name: gitea-data
        hostPath:
          path: /gitea-data
          type: Directory
status: {}
